# Changes here will be overwritten by Copier
_commit: 5.0.2
_src_path: https://github.com/DiamondLightSource/python-copier-template.git
author_email: hyperrealist@pm.me
author_name: hyperrealist
description: A mlx runtiume wrapper with kv cache ops
distribution_name: mlx-kv-server
docker: false
docs_type: sphinx
git_platform: github.com
github_org: distilledecho
package_name: mlx_kv_server
pypi: false
repo_name: mlx-kv-server
strict_typing: true
type_checker: pyright
